
DEF_OPERATION(BOND, ";")
DEF_OPERATION(ASSIGNMENT,     "=")
DEF_OPERATION(IF,             "if")
DEF_OPERATION(WHILE,          "while")
DEF_OPERATION(VAR_DEFINITION, "var_def")

DEF_OPERATION(MAIN,                   "main")
DEF_OPERATION(FUNCTION_DEFINITION,    "func_def")
DEF_OPERATION(FUNCTION_SPECIFICATION, "spec")
DEF_OPERATION(CALL,                   "call")
DEF_OPERATION(RTN,                    "return")

DEF_OPERATION(ELEM_IN,  "scan")
DEF_OPERATION(ELEM_OUT, "print")

DEF_OPERATION(ADD,  "+")
DEF_OPERATION(SUB,  "-")
DEF_OPERATION(MUL,  "*")
DEF_OPERATION(DIV,  "/")
DEF_OPERATION(POW,  "^")

